name: Tests + Linting Python
on:
  pull_request:
  push:
    branches: [master]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install flake8 pytest
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pytest
